import {
  ApprovalStatus,
  ApprovalType,
  CommentVisibility,
  CompanyRole,
  Priority,
  ProjectStatus,
  TaskStatus,
  TimeEntryType,
  TimerState,
  UserRole,
  type ApprovalRequest,
  type Comment,
  type Project,
  type Task,
  type TimeEntry,
  type User,
} from "../../../shared/index.js";

const now = new Date().toISOString();

export const demoUsers: Array<User & { password: string }> = [
  {
    id: "admin-1",
    email: "admin .local",
    password: "Admin@123",
    fullName: "System Admin",
    userRole: UserRole.ADMIN,
    companyRole: CompanyRole.MANAGER,
    managerId: null,
    isActive: true,
    timezone: "Asia/Kolkata",
    createdAt: now,
    updatedAt: now,
    lastLoginAt: now,
  },
  {
    id: "manager-1",
    email: "manager .local",
    password: "Manager@123",
    fullName: "Rohan Mehta",
    userRole: UserRole.MANAGER,
    companyRole: CompanyRole.MANAGER,
    managerId: null,
    isActive: true,
    timezone: "Asia/Kolkata",
    createdAt: now,
    updatedAt: now,
    lastLoginAt: now,
  },
  {
    id: "employee-1",
    email: "employee .local",
    password: "Employee@123",
    fullName: "Utkarsh Kumar",
    userRole: UserRole.EMPLOYEE,
    companyRole: CompanyRole.ANALYST,
    managerId: "manager-1",
    isActive: true,
    timezone: "Asia/Kolkata",
    createdAt: now,
    updatedAt: now,
    lastLoginAt: now,
  },
];

export const demoProjects: Project[] = [
  {
    id: "project-1",
    code: "BFSI-001",
    name: "Credit Rating - BFSI",
    description: "Financial modeling and sector review",
    managerId: "manager-1",
    status: ProjectStatus.ACTIVE,
    startDateUtc: now,
    targetEndDateUtc: new Date(Date.now() + 14 * 86400000).toISOString(),
    createdAt: now,
    updatedAt: now,
  },
];

export const demoTasks: Task[] = [
  {
    id: "task-1",
    projectId: "project-1",
    activityId: "activity-1",
    title: "Model Audit",
    description: "Perform the financial model audit for BFSI review",
    assigneeId: "employee-1",
    createdByManagerId: "manager-1",
    priority: Priority.HIGH,
    status: TaskStatus.WIP,
    estimatedHours: 8,
    loggedMinutes: 270,
    dueDateUtc: new Date(Date.now() + 2 * 86400000).toISOString(),
    startedAtUtc: now,
    completedAtUtc: null,
    approvalPendingSinceUtc: null,
    rejectionReason: null,
    lastTimerEntryId: "entry-1",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-2",
    projectId: "project-1",
    activityId: "activity-2",
    title: "Regression Testing",
    description: "Validate data analytics updates",
    assigneeId: "employee-1",
    createdByManagerId: "manager-1",
    priority: Priority.MEDIUM,
    status: TaskStatus.ON_HOLD,
    estimatedHours: 6,
    loggedMinutes: 75,
    dueDateUtc: new Date(Date.now() + 4 * 86400000).toISOString(),
    startedAtUtc: now,
    completedAtUtc: null,
    approvalPendingSinceUtc: null,
    rejectionReason: null,
    lastTimerEntryId: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoTimeEntries: TimeEntry[] = [
  {
    id: "entry-1",
    taskId: "task-1",
    employeeId: "employee-1",
    projectId: "project-1",
    activityId: "activity-1",
    entryType: TimeEntryType.TIMER,
    timerState: TimerState.RUNNING,
    startTimeUtc: new Date(Date.now() - 84 * 60000).toISOString(),
    endTimeUtc: null,
    durationSeconds: 84 * 60,
    durationMinutes: 84,
    description: "Model audit run",
    isSubmittedForApproval: false,
    approvalRequestId: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoApprovals: ApprovalRequest[] = [
  {
    id: "approval-1",
    type: ApprovalType.MANUAL_LOG,
    taskId: "task-2",
    timeEntryId: "entry-2",
    requestedBy: "employee-1",
    reviewedBy: null,
    status: ApprovalStatus.PENDING,
    reason: "Client feedback delayed testing",
    managerComment: null,
    payload: { requestedMinutes: 90 },
    requestedAtUtc: now,
    reviewedAtUtc: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoComments: Comment[] = [
  {
    id: "comment-1",
    taskId: "task-1",
    authorId: "manager-1",
    body: "Please validate assumptions before final submission.",
    visibility: CommentVisibility.SHARED,
    createdAt: now,
    updatedAt: now,
  },
];
